## ------------------------------------------------------------------------ ##
## Fig. 4M
## ------------------------------------------------------------------------ ##

## Helper setup

helper_configs:
  - [config, common]
  - [config, net_astro-exvivo_repeat.yaml]
hive_root: ['..', data]

# Outputs
output_parent: ['..', output]
notebook_stem: net_astro-py-

## Reproducibility

random_seed: 274957392

## Analyses
condition_key: condition
condition: Glu

repeats_compare:
  - [1, 2]
  - [1, 3]
  - [2, 3]

analysis: wt-repeat-70
event_type: prop
output_names:
  overlap_raster: s7c-overlap_raster


## ************************************************************************ ##
## Key parameters

## Propagation / static split
prop_threshold: 1. # um

coreg_key: cell_global_coreg

responders:
  window_pre: [-60, 0]
  window_post: [300, 420]

  ratio_threshold: 1.5
  min_pre: 1

responder_fractions:
  unit_group_key: cell_global_all
  block_key: dataset_id_all
  pair_key: ~

  n_boot: 10000
  hierarchy_boot:
    - dataset_id_all
    - cell_global_all
  
  n_perm: 10000


## ************************************************************************ ##


## Plotting

significance_plot:
  start: 1.1
  spacing: 0.12